Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 570, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 553, in main
    known_paths = venv(known_paths)
  File "/usr/lib/python3.6/site.py", line 490, in venv
    addsitepackages(known_paths, [sys.prefix])
  File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.6/site.py", line 213, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.6/site.py", line 174, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/usr/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/usr/lib/python3.6/collections/__init__.py", line 26, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
KeyboardInterrupt
Command exited with non-zero status 1
0.02user 0.00system 0:00.02elapsed 100%CPU (0avgtext+0avgdata 9000maxresident)k
0inputs+8outputs (0major+949minor)pagefaults 0swaps
Command terminated by signal 2
0.01user 0.00system 0:00.01elapsed 100%CPU (0avgtext+0avgdata 6924maxresident)k
0inputs+0outputs (0major+565minor)pagefaults 0swaps
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 570, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 553, in main
    known_paths = venv(known_paths)
  File "/usr/lib/python3.6/site.py", line 490, in venv
    addsitepackages(known_paths, [sys.prefix])
  File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.6/site.py", line 213, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.6/site.py", line 174, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/usr/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/usr/lib/python3.6/collections/__init__.py", line 26, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
KeyboardInterrupt
Command exited with non-zero status 1
0.02user 0.00system 0:00.02elapsed 100%CPU (0avgtext+0avgdata 8856maxresident)k
0inputs+0outputs (0major+941minor)pagefaults 0swaps
Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 30, in <module>
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/multiarray.py", line 1599, in <module>
    def datetime_as_string(arr, unit=None, timezone=None, casting=None):
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/overrides.py", line 209, in decorator
    docs_from_dispatcher=docs_from_dispatcher)(implementation)
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/overrides.py", line 181, in decorator
    source, filename='<__array_function__ internals>', mode='exec')
KeyboardInterrupt
Command exited with non-zero status 1
0.86user 0.99system 0:00.10elapsed 1800%CPU (0avgtext+0avgdata 20564maxresident)k
0inputs+16outputs (0major+3171minor)pagefaults 0swaps
Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 26, in <module>
    from dataclasses import dataclass, field
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/dataclasses.py", line 5, in <module>
    import inspect
  File "/usr/lib/python3.6/inspect.py", line 1469, in <module>
    FrameInfo = namedtuple('FrameInfo', ('frame',) + Traceback._fields)
  File "/usr/lib/python3.6/collections/__init__.py", line 429, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Command exited with non-zero status 1
0.04user 0.00system 0:00.05elapsed 100%CPU (0avgtext+0avgdata 15112maxresident)k
8inputs+0outputs (0major+2440minor)pagefaults 0swaps
Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 30, in <module>
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/__init__.py", line 22, in <module>
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/overrides.py", line 9, in <module>
    from numpy.compat._inspect import getargspec
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/compat/__init__.py", line 12, in <module>
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/compat/py3k.py", line 21, in <module>
    from pathlib import Path, PurePath
  File "/usr/lib/python3.6/pathlib.py", line 14, in <module>
    from urllib.parse import quote_from_bytes as urlquote_from_bytes
  File "/usr/lib/python3.6/urllib/parse.py", line 323, in <module>
    class ParseResult(_ParseResultBase, _NetlocResultMixinStr):
KeyboardInterrupt
Command exited with non-zero status 1
0.59user 0.86system 0:00.09elapsed 1520%CPU (0avgtext+0avgdata 20192maxresident)k
0inputs+0outputs (0major+3090minor)pagefaults 0swaps
